services:
  frontend:
    build:
      context: frontend
    environment:
      - VITE_BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - VITE_BACKEND_PORT=3000
    ports:
      - 8080:8080
    networks:
      - public
    depends_on:
      - backend

  backend:
    build:
      context: backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - 3000:3000
    networks:
      - public
      - private
 
networks:
  public:
  private:
