name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  get-ip:
    name: Get IP
    runs-on: self-hosted
    outputs:
      ip: ${{ steps.getip.outputs.IP }}
    steps:
      - name: Retrive IP Address
        id: getip
        run: echo "ip=$(curl ifconfig.me)" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: get-ip
    env:
      BACKEND_BASE_URL: ${{ needs.get-ip.outputs.ip }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker-compose build
      - name: Print config
        run: docker-compose config
      - name: Run
        run: VITE_BACKEND_BASE_URL=${BACKEND_BASE_URL} docker-compose -f compose.yaml up -d
