name: CI/CD Pipeline for AWS EC2 deployment

on:
  push:
    branches:
      - "main"

jobs:
  get-ip:
    name: Get IP
    runs-on: self-hosted
    outputs:
      ip: ${{ steps.getip.outputs.IP }}
    steps:
      - name: Retrive IP Address
        id: getip
        run: echo "ip=$(curl ifconfig.me)" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: get-ip
    env:
      BACKEND_BASE_URL: ${{ needs.get-ip.outputs.ip }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_BUCKET_DOMAIN: ${{ secrets.S3_BUCKET_DOMAIN }}
      MFA_EMAIL: ${{ secrets.MFA_EMAIL }}
      MFA_PASSWORD: ${{ secrets.MFA_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: docker compose up --build -d
      - name: Remove unused images
        run: docker image prune -af
