name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrive IP Address
        id: getip
        run: echo "ip=$(curl ifconfig.me)" >> "$GITHUB_OUTPUT"
      - name: Build
        env:
          BACKEND_BASE_URL: ${{ steps.getip.outputs.ip }}
        run: docker-compose build
      - name: Print config
        run: docker-compose config
      - name: Run
        run: docker-compose -f compose.yaml up -d
