name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    env:
      BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Build and test
        run: docker-compose up -d
